version: '3'
services:
  mysql-primary:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    command: --server-id=1 --log-bin=mysql-bin

  mysql-replica-1:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    command: --server-id=2 --log-bin=mysql-bin --read-only=1

  mysql-replica-2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"
    command: --server-id=3 --log-bin=mysql-bin --read-only=1
