local con = sysbench.sql.driver():connect()
function select_query()
    con:query("SELECT EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr, SUM(B.UMSATZ) AS UmsatzProJahr FROM KUNDEN K JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM);")
    con:query("SELECT EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr, K.LAND AS Land, SUM(B.UMSATZ) AS Gesamtumsatz FROM KUNDEN K JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN WHERE EXTRACT(YEAR FROM B.BESTELLDATUM) = 2020 GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM), K.LAND;")
    con:query("SELECT EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr, K.LAND AS Land, SUM(B.UMSATZ) AS Gesamtumsatz FROM KUNDEN K JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN WHERE K.LAND = 'Germany' GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM), K.LAND;")
    con:query("SELECT EXTRACT(YEAR FROM B.BESTELLDATUM) AS Jahr, K.LAND AS Land, SUM(B.UMSATZ) AS Gesamtumsatz FROM KUNDEN K JOIN BESTELLUNG B ON K.KUNDEN_ID = B.FK_KUNDEN GROUP BY EXTRACT(YEAR FROM B.BESTELLDATUM), K.LAND HAVING SUM(B.UMSATZ) > 2500;")
end

function event()
    select_query()
end