name: Benchmark Workflow

on:
  push:
    paths:
      - 'Projects/**'
      - 'Tools/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [high-count, low-count, b-tree-query-differences, selectivity-change, hash-query-differences, join-type]

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      TIME: 8
      THREADS: 1
      EVENTS: 0
      REPORT_INTERVAL: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sysbench
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      # Dynamically check for changed scripts
      - name: Detect Changed Files
        id: changes
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only HEAD..origin/main)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Map Changes to Scripts
        id: map_scripts
        run: |
          CHANGED_FILES="${{ steps.changes.outputs.changed_files }}"
          declare -A SCRIPTS_TO_RUN=()

          # Map changes to their corresponding test types
          if [[ "$CHANGED_FILES" =~ "Projects/Index/B_Tree/Scripts/count_row_changes/" ]]; then
            SCRIPTS_TO_RUN["high-count"]=true
            SCRIPTS_TO_RUN["low-count"]=true
          fi

          if [[ "$CHANGED_FILES" =~ "Projects/Index/Hash/Scripts/query_differences" ]]; then
            SCRIPTS_TO_RUN["hash-query-differences"]=true
          fi

          if [[ "$CHANGED_FILES" =~ "Projects/Join_Typ/Scripts/" ]]; then
            SCRIPTS_TO_RUN["join-type"]=true
          fi

          if [[ "$CHANGED_FILES" =~ "Projects/Index/Hash/Scripts/selectivity_changes" ]]; then
            SCRIPTS_TO_RUN["selectivity-change"]=true
          fi

          # Map the matrix jobs based on the detected scripts
          SCRIPTS=""
          for key in "${!SCRIPTS_TO_RUN[@]}"; do
            SCRIPTS+="$key,"
          done

          echo "Scripts to run based on changes: $SCRIPTS"
          echo "::set-output name=scripts::$SCRIPTS"

      - name: Check if the current matrix test should run
        run: |
          if [[ "${{ steps.map_scripts.outputs.scripts }}" == *"${{ matrix.test-type }}"* ]]; then
            echo "Running script for ${{ matrix.test-type }}"
          else
            echo "Skipping script for ${{ matrix.test-type }}"
            exit 0
          fi

      # Run the actual script
      - name: Run sysbench script
        run: |
          chmod +x Tools/sysbench_script.sh
          if [ "${{ matrix.test-type }}" == "high-count" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/B_Tree/high_counts" \
              -len "500,5000" \
              -script:"./Projects/Index/B_Tree/Scripts/count_row_changes/with_index:true" \
              -script:"./Projects/Index/B_Tree/Scripts/count_row_changes/without_index:true"
          elif [ "${{ matrix.test-type }}" == "low-count" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/B_Tree/low_counts" \
              -len "10,50" \
              -script:"./Projects/Index/B_Tree/Scripts/count_row_changes/with_index:true" \
              -script:"./Projects/Index/B_Tree/Scripts/count_row_changes/without_index:true"
          elif [ "${{ matrix.test-type }}" == "b-tree-query-differences" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/B_Tree/query_differences" \
              -script:"./Projects/Index/B_Tree/Scripts/query_differences:false"
          elif [ "${{ matrix.test-type }}" == "selectivity-change" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/Hash/selectivity_changes" \
              -len "10,100,500" \
              -script:"./Projects/Index/Hash/Scripts/selectivity_changes:true"
          elif [ "${{ matrix.test-type }}" == "hash-query-differences" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/Hash/query_differences" \
              -script:"./Projects/Index/Hash/Scripts/query_differences:false"
          elif [ "${{ matrix.test-type }}" == "join-type" ]; then
            Tools/sysbench_script.sh \
              -out "./Output/Join_Typ" \
              -len "1,64" \
              -script:"./Projects/Join_Typ/Scripts/int_queries:false" \
              -script:"./Projects/Join_Typ/Scripts/varchar_queries:true"
          fi

      - name: Stop MySQL container
        run: |
          docker stop mysql-${{ matrix.test-type }}
          docker rm mysql-${{ matrix.test-type }}

      - name: Upload output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: combined_output
          path: Output