name: Benchmark Workflow

on:
  push:
    paths:
      - 'Projects/**'
      - 'Tools/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [high-count, low-count, b-tree-query-differences, selectivity-change, hash-query-differences, join-type]

    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Detect Changed Files
      - name: Detect Changed Files
        id: changes
        run: |
          git fetch origin main --depth=1
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      # Step 3: Map Changes to Scripts
      - name: Map Changes to Scripts
        id: map_scripts
        run: |
          CHANGED_FILES="${{ steps.changes.outputs.changed_files }}"
          declare -A SCRIPTS_TO_RUN=()

          # Define mapping of directories to scripts
          if [[ "$CHANGED_FILES" =~ "Projects/Index/B_Tree/Scripts/count_row_changes/" ]]; then
            SCRIPTS_TO_RUN["high-count"]=true
            SCRIPTS_TO_RUN["low-count"]=true
          fi
          if [[ "$CHANGED_FILES" =~ "Projects/Index/Hash/Scripts/query_differences" ]]; then
            SCRIPTS_TO_RUN["hash-query-differences"]=true
          fi

          # Collect test types to run
          SCRIPTS=""
          for key in "${!SCRIPTS_TO_RUN[@]}"; do
            SCRIPTS+="$key,"
          done

          echo "Scripts to run: $SCRIPTS"
          echo "::set-output name=scripts::$SCRIPTS"

      # Step 4: Run Scripts
      - name: Run Selected Test Types
        run: |
          if [[ "${{ steps.map_scripts.outputs.scripts }}" == *"${{ matrix.test-type }}"* ]]; then
            echo "Running script for ${{ matrix.test-type }}"
            # Add commands to run the selected script here.
          else
            echo "Skipping ${{ matrix.test-type }}, no changes."
          fi

      # Step 5: Upload Combined Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: combined_output
          path: ./Output/